name: create executables
run-name: build for commit "${{ github.event.head_commit.message }}" (${{ github.sha }})
on: [push]
permissions:
  contents: write
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun build --compile --target=bun-windows-x64 main.js --outfile ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_win.exe
      - run: bun build --compile --target=bun-linux-x64 main.js --outfile ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_linux
      - run: bun build --compile --target=bun-darwin-arm64 main.js --outfile ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_osx-arm
      - run: bun build --compile --target=bun-darwin-x64 main.js --outfile ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_osx-x64
      - name: Upload windows-executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_win.exe
          path: ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_win.exe
      - name: Upload linux-executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_linux
          path: ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_linux
      - name: Upload macos-arm executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_osx-arm
          path: ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_osx-arm
      - name: Upload macos-x64 executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_osx-x64
          path: ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_osx-x64
      - name: Upload config file
        uses: actions/upload-artifact@v4
        with:
          name: config.toml
          path: config.toml
      - run: mv ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_osx-x64 ${{ github.event.repository.name }}_${{ github.ref_name }}_osx-x64
        if: startsWith(github.ref, 'refs/tags/')
      - run: mv ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_osx-arm ${{ github.event.repository.name }}_${{ github.ref_name }}_osx-arm
        if: startsWith(github.ref, 'refs/tags/')
      - run: mv ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_linux ${{ github.event.repository.name }}_${{ github.ref_name }}_linux
        if: startsWith(github.ref, 'refs/tags/')
      - run: mv ${{ github.event.repository.name }}_${{ env.COMMIT_SHORT_SHA }}_win.exe ${{ github.event.repository.name }}_${{ github.ref_name }}_win.exe
        if: startsWith(github.ref, 'refs/tags/')
      - run: |
          tagAnnotationMessage=$(git for-each-ref refs/tags/${{  github.ref_name }} --format='%(contents)')
          echo "TAG_ANNOTATION_MESSAGE=$tagAnnotationMessage" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{ env.TAG_ANNOTATION_MESSAGE }}
          files: |
            ${{ github.event.repository.name }}_${{  github.ref_name }}_osx-arm
            ${{ github.event.repository.name }}_${{  github.ref_name }}_osx-x64
            ${{ github.event.repository.name }}_${{  github.ref_name }}_linux
            ${{ github.event.repository.name }}_${{  github.ref_name }}_win.exe
            config.toml
